#!/usr/bin/env python3
import os
import glob
import pandas as pd
import argparse
import xml.etree.ElementTree as ET

XML_TEST_DIR = "images/test"
XML_TRAIN_DIR = "images/train"
CSV_TEST_FILE = "annotations/test_labels.csv"
CSV_TRAIN_FILE = "annotations/train_labels.csv"

def xml_to_csv(path):
    """Iterates through all .xml files (generated by labelImg) in a given directory and combines them in a single Pandas datagrame.

    Parameters:
    ----------
    path : {str}
        The path containing the .xml files
    Returns
    -------
    Pandas DataFrame
        The produced dataframe
    """

    xml_list = []
    for xml_file in glob.glob(path + '/*.xml'):
        tree = ET.parse(xml_file)
        root = tree.getroot()
        for member in root.findall('object'):
            value = (root.find('filename').text,
                    int(root.find('size')[0].text),
                    int(root.find('size')[1].text),
                    member[0].text,
                    int(member[4][0].text),
                    int(member[4][1].text),
                    int(member[4][2].text),
                    int(member[4][3].text)
                    )
            xml_list.append(value)
    column_name = ['filename', 'width', 'height',
                'class', 'xmin', 'ymin', 'xmax', 'ymax']
    xml_df = pd.DataFrame(xml_list, columns=column_name)
    return xml_df


def main():
    xml_df_test = xml_to_csv(XML_TEST_DIR)
    xml_df_test.to_csv(CSV_TEST_FILE, index=None)

    xml_df_train = xml_to_csv(XML_TRAIN_DIR)
    xml_df_train.to_csv(CSV_TRAIN_FILE, index=None)

if __name__ == '__main__':
    main()
